webtalk_init -webtalk_dir E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_lyf/Lab5_lyf.sim/sim_1/behav/xsim/xsim.dir/pipeline2_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 16 00:46:55 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0589ecd3-6a99-4f83-bbfb-b15b3410c115" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "77ec4dd9ea7c4b7ea13a1e1a2e9d60b3" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12600K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3686 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6852_KB" -context "xsim\\usage"
webtalk_transmit -clientid 259888807 -regid "" -xml E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_lyf/Lab5_lyf.sim/sim_1/behav/xsim/xsim.dir/pipeline2_behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_lyf/Lab5_lyf.sim/sim_1/behav/xsim/xsim.dir/pipeline2_behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_lyf/Lab5_lyf.sim/sim_1/behav/xsim/xsim.dir/pipeline2_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
