webtalk_init -webtalk_dir E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_vvd/Lab5_vvd.sim/sim_1/behav/xsim/xsim.dir/tb__behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Nov 16 09:53:35 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2902540" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "0589ecd3-6a99-4f83-bbfb-b15b3410c115" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "08b2998baad0495494ce4cd18dbeb00a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "154" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12600K" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3686 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "18 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "10000" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "12628_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1600859943 -regid "" -xml E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_vvd/Lab5_vvd.sim/sim_1/behav/xsim/xsim.dir/tb__behav/webtalk/usage_statistics_ext_xsim.xml -html E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_vvd/Lab5_vvd.sim/sim_1/behav/xsim/xsim.dir/tb__behav/webtalk/usage_statistics_ext_xsim.html -wdm E:/Semesters/FA22/VE370/Labs/Lab5/Lab5_vvd/Lab5_vvd.sim/sim_1/behav/xsim/xsim.dir/tb__behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
